### ISSUE TITLE
Change page error

### ISSUE THREAD

**Issue by arturekdev** [Phoenix616/InventoryGui#34]
#### Used Version
1.4.3
 
#### Full Log
```
13:00:56 ERROR]: [mineAuctions] Exception while trying to run action for click on StaticGuiElement in slot 37 of &8Lista auckji GUI!
[13:00:56 WARN]: java.lang.NoSuchMethodError: de.themoep.inventorygui.InventoryGui.getPageNumber(Lorg/bukkit/entity/HumanEntity;)I
[13:00:56 WARN]:        at pl.mineAuctions.gui.list.ListGuiService.lambda$open$2(ListGuiService.java:87)
[13:00:56 WARN]:        at de.themoep.inventorygui.InventoryGui$GuiListener.onInventoryClick(InventoryGui.java:821)
[13:00:56 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[13:00:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:00:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:00:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2663)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1214)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1207)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1183)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1027)
[13:00:56 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179)
[13:00:56 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

#### What is happening?
If player click next page item throw this error.

#### Code
```
            if ((gui.getPageNumber(player) - 1) != -1) {
                gui.setPageNumber(player, gui.getPageNumber(player) - 1);
            }
```

**Comment by Phoenix616** [comment]
This error is only possible if you have the wrong version of the library loaded/shaded in the same package. Please make sure that you always relocate your libraries when shading to avoid conflicts with other plugins also not doing that (or use a server software like Paper which prioritises classes in your own class loader over the ones from other plugins)
