### ISSUE TITLE
Nullpointer when i do gui.show

### ISSUE THREAD

**Issue by deadman96385** [Phoenix616/InventoryGui#4]
I am targeting against 1.14.2, I am passing the player to the function via the sender arg in the Oncommand function and line 163 is the gui.show line. I am not sure what could be causing the null pointer

``` 
           } else if (args[0].equalsIgnoreCase("menu")) {
                if (args.length == 1) {
                    Player p = ((Player) sender).getPlayer();
                    GuiElementGroup group = new GuiElementGroup('x');
                    InventoryGui gui = new InventoryGui(plugin, p, "&cOnline&4Players", plugin.getConfig().getStringList("matrix").toArray(new String[0]));
                    gui.addElement(new GuiPageElement('b', new ItemStack(Material.COAL, 1), GuiPageElement.PageAction.PREVIOUS, "&cPREVIOUS"));
                    gui.addElement(new GuiPageElement('f', new ItemStack(Material.CHARCOAL, 1), GuiPageElement.PageAction.NEXT, "&aNEXT"));
                    gui.setFiller(new ItemStack(Material.GRAY_STAINED_GLASS, 1));
                    group.setFiller(gui.getFiller());
                    gui.addElement(group);
                    gui.show(p);
                }
            }



The error i get when i run the command is

[04:07:35 INFO]: deadman96385 issued server command: /oxidepunch menu
[04:07:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'oxidepunch' in plugin OxidePunch v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.2.jar:git-Paper-74]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-74]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1832) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1640) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-74]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-74]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(Unknown Source) ~[?:1.8.0_181]
        at de.themoep.inventorygui.InventoryGui.replaceVars(InventoryGui.java:951) ~[?:?]
        at de.themoep.inventorygui.InventoryGui.build(InventoryGui.java:431) ~[?:?]
        at de.themoep.inventorygui.InventoryGui.build(InventoryGui.java:420) ~[?:?]
        at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:443) ~[?:?]
        at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:398) ~[?:?]
        at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:389) ~[?:?]
        at com.oxide.staffpunch.Main.onCommand(Main.java:163) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.2.jar:git-Paper-74]
        ... 17 more

**Comment by Phoenix616** [comment]
1497ed90314f3506bc7641d9e11b514bf302f773 should have fixed that, if it didn't please reply here.
