### ISSUE TITLE
error :(

### ISSUE THREAD

**Issue by Minecon724** [Phoenix616/InventoryGui#40]
```
05.06 15:19:28 [Server] ERROR null
05.06 15:19:28 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'kolor' in plugin BoardPVP v1.0.0
05.06 15:19:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[server.jar:]
05.06 15:19:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[server.jar:]
05.06 15:19:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:775) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1490) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1294) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:56) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7) ~[server.jar:]
05.06 15:19:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
05.06 15:19:28 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[server.jar:]
05.06 15:19:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[server.jar:]
05.06 15:19:28 [Server] INFO at java.lang.Thread.run(Thread.java:829) ~[?:?]
05.06 15:19:28 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/Nameable
05.06 15:19:28 [Server] INFO at de.themoep.inventorygui.InventoryGui.replaceVars(InventoryGui.java:1381) ~[?:?]
05.06 15:19:28 [Server] INFO at de.themoep.inventorygui.InventoryGui.lambda$new$3(InventoryGui.java:210) ~[?:?]
05.06 15:19:28 [Server] INFO at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:651) ~[?:?]
05.06 15:19:28 [Server] INFO at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:634) ~[?:?]
05.06 15:19:28 [Server] INFO at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:576) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:567) ~[?:?]
05.06 15:19:31 [Server] INFO at pl.minecon724.boardpvp.Commands.onCommand(Commands.java:57) ~[?:?]
05.06 15:19:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:]
05.06 15:19:31 [Server] INFO ... 15 more
05.06 15:19:31 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.Nameable
05.06 15:19:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:94) ~[server.jar:]
05.06 15:19:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[server.jar:]
05.06 15:19:31 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
05.06 15:19:31 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.replaceVars(InventoryGui.java:1381) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.lambda$new$3(InventoryGui.java:210) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:651) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:634) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:576) ~[?:?]
05.06 15:19:31 [Server] INFO at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:567) ~[?:?]
05.06 15:19:31 [Server] INFO at pl.minecon724.boardpvp.Commands.onCommand(Commands.java:57) ~[?:?]
05.06 15:19:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:]
05.06 15:19:31 [Server] INFO ... 15 more
```

**Comment by Minecon724** [comment]
uhh, I'm still getting this error?

**Comment by Minecon724** [comment]
the error is the same. and how can I check the version? I've updated the pom.xml a few mins ago

**Comment by Phoenix616** [comment]
Either check if the code is in your built jar or check the md5sum of the file in your cache maven repo.
