### ISSUE TITLE
Item duplication: NullPointerException on double click when I move storaged items to the cursor

### ISSUE THREAD

**Issue by FaMa91** [Phoenix616/InventoryGui#48]
### What is happening?

![immagine](https://github.com/Phoenix616/InventoryGui/assets/13115141/9c4532ed-512c-4056-9974-c41e7f200bc2)
This exception occours if I doubleClick on any item which is placed in more than a slot. This is used to duplicate items.

https://imgur.com/y5A6Lpa

The actual version is a fork from 1.6.1 with just this change to fix an issue:
![immagine](https://github.com/Phoenix616/InventoryGui/assets/13115141/550d7410-d4c8-482a-bf52-da50a87a2096)

### What did you expect to happen?

No exception, no duplication

### Version

1.6.1

### Config

```YAML
?
```

### Server/system Version

Paper 1.19.4

### Log

```shell
[22:23:17] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Feudal v1.19
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.HumanEntity.getUniqueId()" because "player" is null
	at libs.feudal.themoep.InventoryGui.getPageNumber(InventoryGui.java:467) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.GuiStorageElement.getStorageSlot(GuiStorageElement.java:235) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.GuiStorageElement.setStorageItem(GuiStorageElement.java:287) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.GuiStorageElement.setStorageItem(GuiStorageElement.java:276) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.InventoryGui.simulateCollectToCursor(InventoryGui.java:1599) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.InventoryGui.handleInteract(InventoryGui.java:1112) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.InventoryGui.access$500(InventoryGui.java:81) ~[Feudal-3.2.0.jar:?]
	at libs.feudal.themoep.InventoryGui$GuiListener.onInventoryClick(InventoryGui.java:1227) ~[Feudal-3.2.0.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-"483368e"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3196) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-"483368e"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### What other programs/plugins are you running?

I tried with a minimum amount of custom plugins. No interaction with inventory events

**Comment by Phoenix616** [comment]
Fixed with commit `27a52ef6`. Please report such issues private in the future 👀  (I've enabled private reporting on this repo now, unfortunately one needs to do that manually on each GitHub repo :/)
